config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#home'

  resources :games, only: [:new, :create, :index]
  resources :users, only: [:edit, :update]
  resources :tournaments, except: :destroy

  get '/leaderboard' => 'leaderboards#index'
  get '/signup' => 'sessions#new'
  get '/login' => 'sessions#login'
  post '/login' => 'sessions#login_attempt'
  post '/sessions/create' => 'sessions#create'
  match '/signout' => 'sessions#destroy', :as => :signout, via: [:get, :post]
  match 'auth/failure' => 'sessions#failure', via: [:get, :post]

  namespace :api, defaults: { format: 'json' } do
    namespace :v1, defaults: { format: 'json' } do
      get '/leaderboard' => 'leaderboards#index'
      post '/login' => 'authentication#login'
      post '/signup' => 'authentication#signup'

      resources :games, only: [:new, :create]
    end
  end

  get '/:username', to: 'pages#profile', as: 'profile'
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :loser, class_name: 'User', foreign_key: :loser_id
  belongs_to :winner, class_name: 'User', foreign_key: :winner_id

	validate :cannot_play_self

  after_save :update_player_rankings

  serialize :score

  private

  def cannot_play_self
    return if winner_id == 0 && loser_id == 0
    errors.add(:base, 'You cannot play yourself.') if winner_id == loser_id
  end

  def update_player_rankings
    winner_score = winner.ranking.score
    loser_score = loser.ranking.score

    winner.ranking.update_score(loser_score, :win)
    loser.ranking.update_score(winner_score, :loss)
  end
end

app/controllers/api/v1/games_controller.rb
class Api::V1::GamesController < Api::V1::BaseController

  def new
    render json: User.where('id != ?', current_user.id)
  end

  def create
    game = Game.create!(winner_id: current_user.id, loser_id: params[:opponent_id])

    # Change to async whe worker dyno spun up on heroku
    SlackReportingWorker.new.perform(game.id)
    head :created
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def index
		@games = Game.order(id: :desc).limit(5)
	end

	def new
		@users = User.all
	end

	def create
		game = Game.create!(winner_id: current_user.id, loser_id: params[:opponent_id])

		# Change to async whe worker dyno spun up on heroku
    SlackReportingWorker.new.perform(game.id)
		redirect_to leaderboard_path
	end
end

app/views/games/_recent.html.erb
<table>
  <h1>Recent Games</h1>
  <th>Win</th><th></th><th></th><th></th><th>Loss</th>
  <% @games.each do |game| %>
    <tr>
      <td><%= link_to((image_tag game.winner.avatar.url(:medium)), profile_path(game.winner.username)) %></td>
      <td><%= link_to game.winner.username, profile_path(game.winner.username) %></td>
      <td>vs</td>
      <td><%= link_to game.loser.username, profile_path(game.loser.username) %></td>
      <td><%= link_to((image_tag game.loser.avatar.url(:medium)), profile_path(game.loser.username)) %></td>
    </tr>
  <% end %>
</table>

app/views/games/index.html.erb
<div id="games-white">
  <%= render partial: 'games/recent' %>
</div>
<div id="hero">
	<p>
		<a href="/games/new">Create a New Game</a>
		<a href="/leaderboard">View Leaderboard</a>
	</p>
</div>

app/views/games/new.html.erb
<% counter = 1 %>
<div id='opponents'>
	<h1>Congratulations! Who did you defeat:</h1>
	<table>
	<tr>
		<% @users.each do |u| %>
			<% next if u.id == @current_user.id %>
			<td>
				<%=link_to( image_tag(u.avatar.url(:medium), class: 'avatar'), games_path(@current_user.id, opponent_id: u.id), method: :post, title: u.username )%>
				<p><%= u.username %></p>
			</td>
			<% if counter % 5 == 0 %>
				</tr>
				</table><table>
				<tr>
			<% end %>
			<% counter += 1 %>
		<% end %>
	</tr>
	</table>
</div>
<div id="hero">
	<p>
		<a href="/leaderboard">View Leaderboard</a>
		<a href="/games">View Recent Games</a>
	</p>
</div>